---
version: '3.9'
services:
  example:
    image: akvo/akvo-node-18-alpine:20220923.084347.0558ee6
    stdin_open: true
    command: ['./main.sh']
    environment:
      - example=true
    volumes:
      - ./:/app:delegated
    working_dir: /app
    expose:
      - 3000
    ports:
      - 3000:3000
  main:
    image: akvo/akvo-node-18-alpine:20220923.084347.0558ee6
    command: ['./main.sh']
    volumes:
      - ./:/app:delegated
    working_dir: /app
