---
version: '3.9'
services:
  example:
    image: node:17.3.0-alpine3.15
    stdin_open: true
    command: ['./main.sh']
    environment:
      - example=true
    volumes:
      - ./:/app:delegated
    working_dir: /app
    expose:
      - 3000
    ports:
      - 3000:3000
  main:
    image: node:17.3.0-alpine3.15
    command: ['./main.sh']
    volumes:
      - ./:/app:delegated
    working_dir: /app
